project_id = "knputxpnhffskshlakiq"

[functions.create-admin]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.daily-meeting]
verify_jwt = false

[functions.payment-reminder]
verify_jwt = false

[functions.send-manual-email]
verify_jwt = false

[functions.agora-meeting]
verify_jwt = false

[functions.cloudinary-upload]
verify_jwt = false
