import { useState, useEffect } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import { Video, Users, Link, Copy, MessageSquare, Phone, FolderOpen, Hash } from 'lucide-react';
import { ChatRoom } from './ChatRoom';
import { AgoraVideoCall } from './AgoraVideoCall';
import { WorkspaceChat } from './WorkspaceChat';

interface Meeting {
  id: string;
  room_name: string;
  room_url: string;
  title: string;
  description: string;
  created_by: string;
  is_active: boolean;
  participants_count: number;
  created_at: string;
  project_workspace_id?: string;
}

interface ProjectWorkspace {
  id: string;
  project_code: string;
  title: string;
}

const AGORA_APP_ID = '70055c1865ad4462bd0a92cb610707be';

export const MeetingRoom = () => {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const channelFromUrl = searchParams.get('channel');
  
  const [meetings, setMeetings] = useState<Meeting[]>([]);
  const [loading, setLoading] = useState(false);
  const [creating, setCreating] = useState(false);
  const [activeMeeting, setActiveMeeting] = useState<Meeting | null>(null);
  const [activeWorkspace, setActiveWorkspace] = useState<ProjectWorkspace | null>(null);
  const [showChat, setShowChat] = useState(false);
  const [userName, setUserName] = useState('');
  const [pendingChannel, setPendingChannel] = useState<string | null>(null);
  const [accessCode, setAccessCode] = useState('');
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    createdBy: '',
  });

  // Check for channel in URL on mount
  useEffect(() => {
    if (channelFromUrl) {
      setPendingChannel(channelFromUrl);
    }
  }, [channelFromUrl]);

  useEffect(() => {
    fetchMeetings();
  }, []);

  const fetchMeetings = async () => {
    try {
      const { data, error } = await supabase.functions.invoke('agora-meeting', {
        body: { action: 'get-rooms' },
      });

      if (error) throw error;
      if (data.success) {
        setMeetings(data.meetings || []);
      }
    } catch (error: any) {
      console.error('Failed to fetch meetings:', error);
    }
  };

  const createMeeting = async () => {
    if (!formData.title.trim()) {
      toast.error('Meeting title is required');
      return;
    }

    setCreating(true);
    try {
      // First create a project workspace
      const { data: workspaceData, error: workspaceError } = await supabase
        .from('project_workspaces')
        .insert({
          title: formData.title,
          description: formData.description,
          created_by: formData.createdBy || 'Anonymous',
          project_code: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (workspaceError) throw workspaceError;

      const roomName = `meeting-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
      
      const { data, error } = await supabase.functions.invoke('agora-meeting', {
        body: {
          action: 'create-room',
          roomName,
          title: formData.title,
          description: formData.description,
          createdBy: formData.createdBy || 'Anonymous',
          projectWorkspaceId: workspaceData.id,
        },
      });

      if (error) throw error;
      
      if (data.success) {
        toast.success(`Meeting created! Project ID: ${workspaceData.project_code}`);
        setFormData({ title: '', description: '', createdBy: '' });
        fetchMeetings();
      } else {
        throw new Error(data.error);
      }
    } catch (error: any) {
      console.error('Failed to create meeting:', error);
      toast.error(`Failed to create meeting: ${error.message}`);
    } finally {
      setCreating(false);
    }
  };

  const joinMeeting = async (meeting: Meeting) => {
    if (!userName.trim()) {
      toast.error('Please enter your name first');
      return;
    }
    
    // Fetch or create workspace for this meeting
    if (meeting.project_workspace_id) {
      const { data: wsData } = await supabase
        .from('project_workspaces')
        .select('*')
        .eq('id', meeting.project_workspace_id)
        .maybeSingle();
      
      if (wsData) {
        setActiveWorkspace(wsData);
      }
    } else {
      // Create workspace for old meetings that don't have one
      try {
        const { data: newWorkspace, error } = await supabase
          .from('project_workspaces')
          .insert({
            title: meeting.title,
            description: meeting.description || '',
            created_by: meeting.created_by,
            project_code: '', // Auto-generated
          })
          .select()
          .single();
        
        if (!error && newWorkspace) {
          // Update meeting with workspace ID
          await supabase
            .from('meetings')
            .update({ project_workspace_id: newWorkspace.id })
            .eq('id', meeting.id);
          
          setActiveWorkspace(newWorkspace);
          toast.success(`Project ID: ${newWorkspace.project_code}`);
        }
      } catch (err) {
        console.error('Failed to create workspace:', err);
      }
    }
    
    setActiveMeeting(meeting);
    setPendingChannel(null);
  };

  const joinDirectChannel = async () => {
    if (!userName.trim()) {
      toast.error('Please enter your name first');
      return;
    }
    if (!pendingChannel) return;
    
    // Check if this channel already has a meeting with workspace
    const { data: existingMeeting } = await supabase
      .from('meetings')
      .select('*, project_workspaces(*)')
      .eq('room_name', pendingChannel)
      .maybeSingle();
    
    if (existingMeeting) {
      if (existingMeeting.project_workspaces) {
        setActiveWorkspace(existingMeeting.project_workspaces);
      }
      setActiveMeeting(existingMeeting);
    } else {
      // Create workspace for direct join
      const { data: newWorkspace } = await supabase
        .from('project_workspaces')
        .insert({
          title: 'Direct Meeting',
          description: '',
          created_by: userName,
          project_code: '',
        })
        .select()
        .single();
      
      if (newWorkspace) {
        setActiveWorkspace(newWorkspace);
        toast.success(`Project ID: ${newWorkspace.project_code}`);
      }
      
      // Create a temporary meeting object for direct join
      const directMeeting: Meeting = {
        id: 'direct-' + pendingChannel,
        room_name: pendingChannel,
        room_url: pendingChannel,
        title: 'Direct Meeting',
        description: '',
        created_by: userName,
        is_active: true,
        participants_count: 0,
        created_at: new Date().toISOString(),
        project_workspace_id: newWorkspace?.id,
      };
      setActiveMeeting(directMeeting);
    }
    
    setPendingChannel(null);
  };

  const leaveMeeting = () => {
    setActiveMeeting(null);
    setActiveWorkspace(null);
    setShowChat(false);
  };

  const accessWorkspaceByCode = async () => {
    if (!accessCode.trim()) {
      toast.error('Please enter a project code');
      return;
    }
    navigate(`/workspace/${accessCode.trim().toUpperCase()}`);
  };

  const getMeetingLink = (meeting: Meeting) => {
    // Use custom domain for production, fallback to current origin
    const customDomain = 'https://socilet.in';
    const isProduction = !window.location.hostname.includes('lovable');
    const baseUrl = isProduction ? customDomain : window.location.origin;
    return `${baseUrl}/meetings?channel=${meeting.room_name}`;
  };

  const copyLink = (meeting: Meeting) => {
    const meetingLink = getMeetingLink(meeting);
    navigator.clipboard.writeText(meetingLink);
    toast.success('Meeting link copied!');
  };

  if (activeMeeting) {
    return (
      <div className="h-[100dvh] flex flex-col bg-background overflow-hidden">
        {/* Meeting Header - Optimized for mobile */}
        <div className="flex-shrink-0 flex items-center justify-between p-2 sm:p-3 border-b bg-card gap-1 min-h-[48px] sm:min-h-[56px]">
          {/* Left side - Title & Project ID */}
          <div className="flex items-center gap-1 sm:gap-2 min-w-0 flex-1">
            <h2 className="text-xs sm:text-base font-semibold truncate max-w-[100px] sm:max-w-[200px]">{activeMeeting.title}</h2>
            {activeWorkspace && (
              <button
                className="flex items-center gap-0.5 bg-primary/10 text-primary px-1.5 py-0.5 rounded text-[10px] sm:text-xs flex-shrink-0"
                onClick={() => {
                  navigator.clipboard.writeText(activeWorkspace.project_code);
                  toast.success('Project ID copied!');
                }}
              >
                <Hash className="h-2.5 w-2.5 sm:h-3 sm:w-3" />
                <span className="font-mono">{activeWorkspace.project_code}</span>
              </button>
            )}
          </div>
          
          {/* Right side - Action buttons */}
          <div className="flex items-center gap-1 sm:gap-2 flex-shrink-0">
            <Button
              variant="ghost"
              size="icon"
              className="h-8 w-8 sm:h-9 sm:w-9"
              onClick={() => copyLink(activeMeeting)}
              title="Copy Link"
            >
              <Copy className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
            </Button>
            {activeWorkspace && (
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8 sm:h-9 sm:w-9 hidden sm:flex"
                onClick={() => navigate(`/workspace/${activeWorkspace.project_code}`)}
                title="Workspace"
              >
                <FolderOpen className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
              </Button>
            )}
            <Button
              variant={showChat ? "default" : "ghost"}
              size="icon"
              className="h-8 w-8 sm:h-9 sm:w-9"
              onClick={() => setShowChat(!showChat)}
              title="Chat"
            >
              <MessageSquare className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
            </Button>
            <Button 
              variant="destructive" 
              size="sm" 
              className="h-8 px-2 sm:px-3 text-xs sm:text-sm" 
              onClick={leaveMeeting}
            >
              <Phone className="h-3.5 w-3.5 sm:h-4 sm:w-4 sm:mr-1" />
              <span className="hidden sm:inline">Leave</span>
            </Button>
          </div>
        </div>

        {/* Meeting Content */}
        <div className="flex-1 flex overflow-hidden relative">
          {/* Video Area - Always rendered but hidden on mobile when chat is open */}
          <div className={`flex-1 ${showChat ? 'hidden sm:block sm:flex-[2]' : 'w-full'}`}>
            <AgoraVideoCall
              appId={AGORA_APP_ID}
              channelName={activeMeeting.room_name}
              userName={userName}
              onLeave={leaveMeeting}
            />
          </div>

          {/* Chat Sidebar - Full screen on mobile with back button */}
          {showChat && (
            <div className="absolute inset-0 sm:relative sm:inset-auto w-full sm:flex-1 border-l bg-card flex flex-col z-10">
              {/* Mobile Chat Header with Back Button */}
              <div className="flex items-center gap-2 p-2 border-b bg-muted/50 sm:hidden">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setShowChat(false)}
                  className="h-8 px-2"
                >
                  <Video className="h-4 w-4 mr-1" />
                  Back to Video
                </Button>
                <span className="text-sm font-medium flex-1 text-center">Chat</span>
              </div>
              
              {/* Chat Content */}
              <div className="flex-1 overflow-hidden">
                {activeWorkspace ? (
                  <WorkspaceChat
                    workspaceId={activeWorkspace.id}
                    userName={userName}
                    isFromMeeting={true}
                  />
                ) : (
                  <ChatRoom
                    meetingId={activeMeeting.id}
                    userName={userName}
                    onClose={() => setShowChat(false)}
                  />
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto p-4 sm:p-6 space-y-4 sm:space-y-6 max-w-full overflow-x-hidden">
      {/* Direct Join from URL */}
      {pendingChannel && (
        <Card className="border-primary border-2">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-primary">
              <Video className="h-5 w-5" />
              Join Meeting
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              You have been invited to join a meeting. Enter your name below and click Join.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 sm:items-end">
              <div className="flex-1 max-w-md">
                <Label>Your Name *</Label>
                <Input
                  placeholder="Enter your name"
                  value={userName}
                  onChange={(e) => setUserName(e.target.value)}
                  className="mt-1"
                />
              </div>
              <Button onClick={joinDirectChannel} size="lg" className="w-full sm:w-auto">
                <Video className="h-4 w-4 mr-2" />
                Join Meeting
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Access Existing Workspace by Project ID */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FolderOpen className="h-5 w-5" />
            Access Project Workspace
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-muted-foreground">
            Have a Project ID? Enter it below to access chat history and shared files.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 sm:items-end">
            <div className="flex-1 max-w-xs">
              <Label>Project Code</Label>
              <Input
                placeholder="e.g., ABC-1234"
                value={accessCode}
                onChange={(e) => setAccessCode(e.target.value.toUpperCase())}
                className="mt-1 font-mono"
                maxLength={10}
              />
            </div>
            <Button onClick={accessWorkspaceByCode} disabled={!accessCode.trim()} className="w-full sm:w-auto">
              <FolderOpen className="h-4 w-4 mr-2" />
              Open Workspace
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Create Meeting */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Video className="h-5 w-5" />
            Create New Meeting
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            <div>
              <Label>Meeting Title *</Label>
              <Input
                placeholder="e.g., Project Discussion"
                value={formData.title}
                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              />
            </div>
            <div>
              <Label>Your Name</Label>
              <Input
                placeholder="Host name"
                value={formData.createdBy}
                onChange={(e) => setFormData({ ...formData, createdBy: e.target.value })}
              />
            </div>
          </div>
          <div>
            <Label>Description (Optional)</Label>
            <Textarea
              placeholder="What's this meeting about?"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
            />
          </div>
          <Button onClick={createMeeting} disabled={creating}>
            {creating ? 'Creating...' : 'Create Meeting'}
          </Button>
          <p className="text-xs text-muted-foreground">
            A unique Project ID will be generated that you can share for future collaboration.
          </p>
        </CardContent>
      </Card>

      {/* User Name Input - Above Active Meetings */}
      <Card className={pendingChannel ? 'hidden' : ''}>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Users className="h-5 w-5" />
            Enter Your Name First
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground mb-3">
            Please enter your name before joining any meeting
          </p>
          <Input
            placeholder="Enter your name to join meetings"
            value={userName}
            onChange={(e) => setUserName(e.target.value)}
            className="max-w-md"
          />
          {userName.trim() && (
            <p className="text-sm text-primary mt-2">✓ Name set: {userName}</p>
          )}
        </CardContent>
      </Card>

      {/* Active Meetings */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Users className="h-5 w-5" />
            Active Meetings ({meetings.length})
          </CardTitle>
        </CardHeader>
        <CardContent>
          {meetings.length === 0 ? (
            <p className="text-muted-foreground text-center py-8">
              No active meetings. Create one above to get started!
            </p>
          ) : (
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              {meetings.map((meeting: any) => (
                <Card key={meeting.id} className="border">
                  <CardContent className="p-4 space-y-3">
                    <div>
                      <h3 className="font-semibold">{meeting.title}</h3>
                      <p className="text-sm text-muted-foreground line-clamp-2">
                        {meeting.description || 'No description'}
                      </p>
                    </div>
                    {meeting.project_code && (
                      <div className="flex items-center gap-1 bg-primary/10 text-primary px-2 py-1 rounded text-xs w-fit">
                        <Hash className="h-3 w-3" />
                        <span className="font-mono">{meeting.project_code}</span>
                      </div>
                    )}
                    <div className="text-xs text-muted-foreground">
                      Created by: {meeting.created_by}
                    </div>
                    <div className="flex gap-2 flex-wrap">
                      <Button
                        size="sm"
                        className="flex-1"
                        onClick={() => joinMeeting(meeting)}
                      >
                        <Video className="h-4 w-4 mr-1" />
                        Join
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => copyLink(meeting)}
                      >
                        <Link className="h-4 w-4" />
                      </Button>
                      {meeting.project_code && (
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => navigate(`/workspace/${meeting.project_code}`)}
                        >
                          <FolderOpen className="h-4 w-4" />
                        </Button>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};
