// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bblutfbzkfgpihedjknu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJibHV0ZmJ6a2ZncGloZWRqa251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzcxMTUsImV4cCI6MjA2ODc1MzExNX0.myN1gfdxqeJCXsMIij7XbCeRulv0WlQMPjfFFxK5-ow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});