// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcsaviqtmpboykhkvtuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxjc2F2aXF0bXBib3lraGt2dHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjA1NzEsImV4cCI6MjA2ODMzNjU3MX0.TtO0gxBMmndYyFs7hyi77zGRm3jRCc2_jg-h7ypCyx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});